// Mocks generated by Mockito 5.4.4 from annotations
// in workout_tracker/test/presentation/viewmodels/auth_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hive_flutter/hive_flutter.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_tracker/data/datasources/local/program_cache.dart'
    as _i5;
import 'package:workout_tracker/data/models/program_model.dart' as _i7;
import 'package:workout_tracker/domain/entities/user_entity.dart' as _i2;
import 'package:workout_tracker/domain/repositories/i_auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  @override
  _i4.Future<_i2.UserEntity?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.UserEntity?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.UserEntity?>.value(),
      ) as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Future<_i2.UserEntity> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i2.UserEntity?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #authStateChanges,
          [],
        ),
        returnValue: _i4.Stream<_i2.UserEntity?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.UserEntity?>.empty(),
      ) as _i4.Stream<_i2.UserEntity?>);

  @override
  _i4.Future<void> updateUserPreferences({
    String? preferredUnit,
    int? defaultRestTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreferences,
          [],
          {
            #preferredUnit: preferredUnit,
            #defaultRestTime: defaultRestTime,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ProgramCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramCache extends _i1.Mock implements _i5.ProgramCache {
  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void injectBoxesForTest(
    _i6.Box<Map<dynamic, dynamic>>? programsBox,
    _i6.Box<dynamic>? metaBox,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #injectBoxesForTest,
          [
            programsBox,
            metaBox,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool isStaleForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isStaleForUser,
          [userId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i7.ProgramModel> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i7.ProgramModel>[],
        returnValueForMissingStub: <_i7.ProgramModel>[],
      ) as List<_i7.ProgramModel>);

  @override
  _i7.ProgramModel? getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i7.ProgramModel?);

  @override
  _i4.Future<void> replaceAll(
    String? userId,
    List<_i7.ProgramModel>? programs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAll,
          [
            userId,
            programs,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> upsert(_i7.ProgramModel? program) => (super.noSuchMethod(
        Invocation.method(
          #upsert,
          [program],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> remove(String? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
