// Mocks generated by Mockito 5.4.4 from annotations
// in workout_tracker/test/presentation/viewmodels/program_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hive_flutter/hive_flutter.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_tracker/data/datasources/local/exercise_library_cache.dart'
    as _i8;
import 'package:workout_tracker/data/datasources/local/program_cache.dart'
    as _i11;
import 'package:workout_tracker/data/models/exercise_library_model.dart'
    as _i10;
import 'package:workout_tracker/data/models/program_model.dart' as _i12;
import 'package:workout_tracker/domain/entities/exercise_library_entity.dart'
    as _i2;
import 'package:workout_tracker/domain/entities/exercise_log_entity.dart'
    as _i7;
import 'package:workout_tracker/domain/entities/program_entity.dart' as _i3;
import 'package:workout_tracker/domain/entities/workout_session_entity.dart'
    as _i4;
import 'package:workout_tracker/domain/repositories/i_workout_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExerciseLibraryEntity_0 extends _i1.SmartFake
    implements _i2.ExerciseLibraryEntity {
  _FakeExerciseLibraryEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProgramEntity_1 extends _i1.SmartFake implements _i3.ProgramEntity {
  _FakeProgramEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutSessionEntity_2 extends _i1.SmartFake
    implements _i4.WorkoutSessionEntity {
  _FakeWorkoutSessionEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IWorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWorkoutRepository extends _i1.Mock
    implements _i5.IWorkoutRepository {
  @override
  _i6.Future<List<_i2.ExerciseLibraryEntity>> getExerciseLibrary() =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseLibrary,
          [],
        ),
        returnValue: _i6.Future<List<_i2.ExerciseLibraryEntity>>.value(
            <_i2.ExerciseLibraryEntity>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i2.ExerciseLibraryEntity>>.value(
                <_i2.ExerciseLibraryEntity>[]),
      ) as _i6.Future<List<_i2.ExerciseLibraryEntity>>);

  @override
  _i6.Future<_i2.ExerciseLibraryEntity?> getExerciseLibraryById(
          String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseLibraryById,
          [exerciseId],
        ),
        returnValue: _i6.Future<_i2.ExerciseLibraryEntity?>.value(),
        returnValueForMissingStub:
            _i6.Future<_i2.ExerciseLibraryEntity?>.value(),
      ) as _i6.Future<_i2.ExerciseLibraryEntity?>);

  @override
  _i6.Future<_i2.ExerciseLibraryEntity> createLibraryExercise(
          _i2.ExerciseLibraryEntity? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLibraryExercise,
          [exercise],
        ),
        returnValue: _i6.Future<_i2.ExerciseLibraryEntity>.value(
            _FakeExerciseLibraryEntity_0(
          this,
          Invocation.method(
            #createLibraryExercise,
            [exercise],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.ExerciseLibraryEntity>.value(
            _FakeExerciseLibraryEntity_0(
          this,
          Invocation.method(
            #createLibraryExercise,
            [exercise],
          ),
        )),
      ) as _i6.Future<_i2.ExerciseLibraryEntity>);

  @override
  _i6.Future<_i2.ExerciseLibraryEntity> updateLibraryExercise(
          _i2.ExerciseLibraryEntity? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLibraryExercise,
          [exercise],
        ),
        returnValue: _i6.Future<_i2.ExerciseLibraryEntity>.value(
            _FakeExerciseLibraryEntity_0(
          this,
          Invocation.method(
            #updateLibraryExercise,
            [exercise],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.ExerciseLibraryEntity>.value(
            _FakeExerciseLibraryEntity_0(
          this,
          Invocation.method(
            #updateLibraryExercise,
            [exercise],
          ),
        )),
      ) as _i6.Future<_i2.ExerciseLibraryEntity>);

  @override
  _i6.Future<void> deleteLibraryExercise(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLibraryExercise,
          [exerciseId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i2.ExerciseLibraryEntity>> watchExerciseLibrary() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchExerciseLibrary,
          [],
        ),
        returnValue: _i6.Stream<List<_i2.ExerciseLibraryEntity>>.empty(),
        returnValueForMissingStub:
            _i6.Stream<List<_i2.ExerciseLibraryEntity>>.empty(),
      ) as _i6.Stream<List<_i2.ExerciseLibraryEntity>>);

  @override
  _i6.Future<List<_i3.ProgramEntity>> getPrograms() => (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.ProgramEntity>>.value(<_i3.ProgramEntity>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.ProgramEntity>>.value(<_i3.ProgramEntity>[]),
      ) as _i6.Future<List<_i3.ProgramEntity>>);

  @override
  _i6.Future<_i3.ProgramEntity?> getProgramById(String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [programId],
        ),
        returnValue: _i6.Future<_i3.ProgramEntity?>.value(),
        returnValueForMissingStub: _i6.Future<_i3.ProgramEntity?>.value(),
      ) as _i6.Future<_i3.ProgramEntity?>);

  @override
  _i6.Future<_i3.ProgramEntity> createProgram(_i3.ProgramEntity? program) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProgram,
          [program],
        ),
        returnValue: _i6.Future<_i3.ProgramEntity>.value(_FakeProgramEntity_1(
          this,
          Invocation.method(
            #createProgram,
            [program],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.ProgramEntity>.value(_FakeProgramEntity_1(
          this,
          Invocation.method(
            #createProgram,
            [program],
          ),
        )),
      ) as _i6.Future<_i3.ProgramEntity>);

  @override
  _i6.Future<_i3.ProgramEntity> updateProgram(_i3.ProgramEntity? program) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgram,
          [program],
        ),
        returnValue: _i6.Future<_i3.ProgramEntity>.value(_FakeProgramEntity_1(
          this,
          Invocation.method(
            #updateProgram,
            [program],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.ProgramEntity>.value(_FakeProgramEntity_1(
          this,
          Invocation.method(
            #updateProgram,
            [program],
          ),
        )),
      ) as _i6.Future<_i3.ProgramEntity>);

  @override
  _i6.Future<void> deleteProgram(String? programId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProgram,
          [programId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i3.ProgramEntity>> watchPrograms() => (super.noSuchMethod(
        Invocation.method(
          #watchPrograms,
          [],
        ),
        returnValue: _i6.Stream<List<_i3.ProgramEntity>>.empty(),
        returnValueForMissingStub: _i6.Stream<List<_i3.ProgramEntity>>.empty(),
      ) as _i6.Stream<List<_i3.ProgramEntity>>);

  @override
  _i6.Future<_i4.WorkoutSessionEntity?> getActiveWorkoutSession() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveWorkoutSession,
          [],
        ),
        returnValue: _i6.Future<_i4.WorkoutSessionEntity?>.value(),
        returnValueForMissingStub:
            _i6.Future<_i4.WorkoutSessionEntity?>.value(),
      ) as _i6.Future<_i4.WorkoutSessionEntity?>);

  @override
  _i6.Future<_i4.WorkoutSessionEntity> startWorkoutSession({
    required String? programId,
    required String? programName,
    bool? useRestTimer = false,
    int? restTimerDuration = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startWorkoutSession,
          [],
          {
            #programId: programId,
            #programName: programName,
            #useRestTimer: useRestTimer,
            #restTimerDuration: restTimerDuration,
          },
        ),
        returnValue: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #startWorkoutSession,
            [],
            {
              #programId: programId,
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #startWorkoutSession,
            [],
            {
              #programId: programId,
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
      ) as _i6.Future<_i4.WorkoutSessionEntity>);

  @override
  _i6.Future<_i4.WorkoutSessionEntity> startQuickWorkoutSession({
    String? programName = r'Quick Workout',
    bool? useRestTimer = false,
    int? restTimerDuration = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startQuickWorkoutSession,
          [],
          {
            #programName: programName,
            #useRestTimer: useRestTimer,
            #restTimerDuration: restTimerDuration,
          },
        ),
        returnValue: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #startQuickWorkoutSession,
            [],
            {
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #startQuickWorkoutSession,
            [],
            {
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
      ) as _i6.Future<_i4.WorkoutSessionEntity>);

  @override
  _i6.Future<_i4.WorkoutSessionEntity> updateWorkoutSession(
          _i4.WorkoutSessionEntity? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutSession,
          [session],
        ),
        returnValue: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #updateWorkoutSession,
            [session],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #updateWorkoutSession,
            [session],
          ),
        )),
      ) as _i6.Future<_i4.WorkoutSessionEntity>);

  @override
  _i6.Future<_i4.WorkoutSessionEntity> completeWorkoutSession(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeWorkoutSession,
          [sessionId],
        ),
        returnValue: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #completeWorkoutSession,
            [sessionId],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.WorkoutSessionEntity>.value(
            _FakeWorkoutSessionEntity_2(
          this,
          Invocation.method(
            #completeWorkoutSession,
            [sessionId],
          ),
        )),
      ) as _i6.Future<_i4.WorkoutSessionEntity>);

  @override
  _i6.Future<void> cancelWorkoutSession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelWorkoutSession,
          [sessionId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.WorkoutSessionEntity?> getWorkoutSessionById(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSessionById,
          [sessionId],
        ),
        returnValue: _i6.Future<_i4.WorkoutSessionEntity?>.value(),
        returnValueForMissingStub:
            _i6.Future<_i4.WorkoutSessionEntity?>.value(),
      ) as _i6.Future<_i4.WorkoutSessionEntity?>);

  @override
  _i6.Future<List<_i4.WorkoutSessionEntity>> getWorkoutHistory({
    int? limit,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutHistory,
          [],
          {
            #limit: limit,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i6.Future<List<_i4.WorkoutSessionEntity>>.value(
            <_i4.WorkoutSessionEntity>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.WorkoutSessionEntity>>.value(
                <_i4.WorkoutSessionEntity>[]),
      ) as _i6.Future<List<_i4.WorkoutSessionEntity>>);

  @override
  _i6.Future<List<_i4.WorkoutSessionEntity>> getWorkoutHistoryByProgram(
    String? programId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutHistoryByProgram,
          [programId],
          {#limit: limit},
        ),
        returnValue: _i6.Future<List<_i4.WorkoutSessionEntity>>.value(
            <_i4.WorkoutSessionEntity>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.WorkoutSessionEntity>>.value(
                <_i4.WorkoutSessionEntity>[]),
      ) as _i6.Future<List<_i4.WorkoutSessionEntity>>);

  @override
  _i6.Future<List<_i7.ExerciseLogEntity>> getExerciseHistory(
    String? exerciseName, {
    int? limit,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseHistory,
          [exerciseName],
          {
            #limit: limit,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i6.Future<List<_i7.ExerciseLogEntity>>.value(
            <_i7.ExerciseLogEntity>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i7.ExerciseLogEntity>>.value(
                <_i7.ExerciseLogEntity>[]),
      ) as _i6.Future<List<_i7.ExerciseLogEntity>>);

  @override
  _i6.Future<List<String>> getAllExerciseNames() => (super.noSuchMethod(
        Invocation.method(
          #getAllExerciseNames,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<Map<String, dynamic>> getExercisePersonalRecords(
          String? exerciseName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisePersonalRecords,
          [exerciseName],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getExerciseProgressData(
    String? exerciseName, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseProgressData,
          [exerciseName],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<int> getTotalWorkoutCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalWorkoutCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<double> getTotalVolume() => (super.noSuchMethod(
        Invocation.method(
          #getTotalVolume,
          [],
        ),
        returnValue: _i6.Future<double>.value(0.0),
        returnValueForMissingStub: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<int> getCurrentStreak() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentStreak,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
}

/// A class which mocks [ExerciseLibraryCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLibraryCache extends _i1.Mock
    implements _i8.ExerciseLibraryCache {
  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isStale => (super.noSuchMethod(
        Invocation.getter(#isStale),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void injectBoxesForTest(
    _i9.Box<Map<dynamic, dynamic>>? exercisesBox,
    _i9.Box<dynamic>? metaBox,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #injectBoxesForTest,
          [
            exercisesBox,
            metaBox,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i10.ExerciseLibraryModel> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i10.ExerciseLibraryModel>[],
        returnValueForMissingStub: <_i10.ExerciseLibraryModel>[],
      ) as List<_i10.ExerciseLibraryModel>);

  @override
  _i6.Future<void> replaceAll(List<_i10.ExerciseLibraryModel>? exercises) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAll,
          [exercises],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> upsert(_i10.ExerciseLibraryModel? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsert,
          [exercise],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ProgramCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramCache extends _i1.Mock implements _i11.ProgramCache {
  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void injectBoxesForTest(
    _i9.Box<Map<dynamic, dynamic>>? programsBox,
    _i9.Box<dynamic>? metaBox,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #injectBoxesForTest,
          [
            programsBox,
            metaBox,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isStaleForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isStaleForUser,
          [userId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i12.ProgramModel> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i12.ProgramModel>[],
        returnValueForMissingStub: <_i12.ProgramModel>[],
      ) as List<_i12.ProgramModel>);

  @override
  _i12.ProgramModel? getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i12.ProgramModel?);

  @override
  _i6.Future<void> replaceAll(
    String? userId,
    List<_i12.ProgramModel>? programs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAll,
          [
            userId,
            programs,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> upsert(_i12.ProgramModel? program) => (super.noSuchMethod(
        Invocation.method(
          #upsert,
          [program],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
