// Mocks generated by Mockito 5.4.4 from annotations
// in workout_tracker/test/data/repositories/workout_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_tracker/data/datasources/remote/firebase_workout_datasource.dart'
    as _i5;
import 'package:workout_tracker/data/models/exercise_library_model.dart' as _i4;
import 'package:workout_tracker/data/models/exercise_log_model.dart' as _i7;
import 'package:workout_tracker/data/models/program_model.dart' as _i2;
import 'package:workout_tracker/data/models/workout_session_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProgramModel_0 extends _i1.SmartFake implements _i2.ProgramModel {
  _FakeProgramModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutSessionModel_1 extends _i1.SmartFake
    implements _i3.WorkoutSessionModel {
  _FakeWorkoutSessionModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExerciseLibraryModel_2 extends _i1.SmartFake
    implements _i4.ExerciseLibraryModel {
  _FakeExerciseLibraryModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseWorkoutDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseWorkoutDataSource extends _i1.Mock
    implements _i5.FirebaseWorkoutDataSource {
  @override
  _i6.Future<List<_i2.ProgramModel>> getPrograms() => (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.ProgramModel>>.value(<_i2.ProgramModel>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i2.ProgramModel>>.value(<_i2.ProgramModel>[]),
      ) as _i6.Future<List<_i2.ProgramModel>>);

  @override
  _i6.Future<_i2.ProgramModel?> getProgramById(String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [programId],
        ),
        returnValue: _i6.Future<_i2.ProgramModel?>.value(),
        returnValueForMissingStub: _i6.Future<_i2.ProgramModel?>.value(),
      ) as _i6.Future<_i2.ProgramModel?>);

  @override
  _i6.Future<_i2.ProgramModel> createProgram(_i2.ProgramModel? program) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProgram,
          [program],
        ),
        returnValue: _i6.Future<_i2.ProgramModel>.value(_FakeProgramModel_0(
          this,
          Invocation.method(
            #createProgram,
            [program],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.ProgramModel>.value(_FakeProgramModel_0(
          this,
          Invocation.method(
            #createProgram,
            [program],
          ),
        )),
      ) as _i6.Future<_i2.ProgramModel>);

  @override
  _i6.Future<_i2.ProgramModel> updateProgram(_i2.ProgramModel? program) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgram,
          [program],
        ),
        returnValue: _i6.Future<_i2.ProgramModel>.value(_FakeProgramModel_0(
          this,
          Invocation.method(
            #updateProgram,
            [program],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.ProgramModel>.value(_FakeProgramModel_0(
          this,
          Invocation.method(
            #updateProgram,
            [program],
          ),
        )),
      ) as _i6.Future<_i2.ProgramModel>);

  @override
  _i6.Future<void> deleteProgram(String? programId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProgram,
          [programId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i2.ProgramModel>> watchPrograms() => (super.noSuchMethod(
        Invocation.method(
          #watchPrograms,
          [],
        ),
        returnValue: _i6.Stream<List<_i2.ProgramModel>>.empty(),
        returnValueForMissingStub: _i6.Stream<List<_i2.ProgramModel>>.empty(),
      ) as _i6.Stream<List<_i2.ProgramModel>>);

  @override
  _i6.Future<_i3.WorkoutSessionModel?> getActiveWorkoutSession() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveWorkoutSession,
          [],
        ),
        returnValue: _i6.Future<_i3.WorkoutSessionModel?>.value(),
        returnValueForMissingStub: _i6.Future<_i3.WorkoutSessionModel?>.value(),
      ) as _i6.Future<_i3.WorkoutSessionModel?>);

  @override
  _i6.Future<_i3.WorkoutSessionModel> startWorkoutSession({
    required String? programId,
    required String? programName,
    bool? useRestTimer = false,
    int? restTimerDuration = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startWorkoutSession,
          [],
          {
            #programId: programId,
            #programName: programName,
            #useRestTimer: useRestTimer,
            #restTimerDuration: restTimerDuration,
          },
        ),
        returnValue: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #startWorkoutSession,
            [],
            {
              #programId: programId,
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #startWorkoutSession,
            [],
            {
              #programId: programId,
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
      ) as _i6.Future<_i3.WorkoutSessionModel>);

  @override
  _i6.Future<_i3.WorkoutSessionModel> startQuickWorkoutSession({
    String? programName = r'Quick Workout',
    bool? useRestTimer = false,
    int? restTimerDuration = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startQuickWorkoutSession,
          [],
          {
            #programName: programName,
            #useRestTimer: useRestTimer,
            #restTimerDuration: restTimerDuration,
          },
        ),
        returnValue: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #startQuickWorkoutSession,
            [],
            {
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #startQuickWorkoutSession,
            [],
            {
              #programName: programName,
              #useRestTimer: useRestTimer,
              #restTimerDuration: restTimerDuration,
            },
          ),
        )),
      ) as _i6.Future<_i3.WorkoutSessionModel>);

  @override
  _i6.Future<_i3.WorkoutSessionModel> updateWorkoutSession(
          _i3.WorkoutSessionModel? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutSession,
          [session],
        ),
        returnValue: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #updateWorkoutSession,
            [session],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #updateWorkoutSession,
            [session],
          ),
        )),
      ) as _i6.Future<_i3.WorkoutSessionModel>);

  @override
  _i6.Future<_i3.WorkoutSessionModel> completeWorkoutSession(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeWorkoutSession,
          [sessionId],
        ),
        returnValue: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #completeWorkoutSession,
            [sessionId],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.WorkoutSessionModel>.value(
            _FakeWorkoutSessionModel_1(
          this,
          Invocation.method(
            #completeWorkoutSession,
            [sessionId],
          ),
        )),
      ) as _i6.Future<_i3.WorkoutSessionModel>);

  @override
  _i6.Future<void> cancelWorkoutSession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelWorkoutSession,
          [sessionId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.WorkoutSessionModel?> getWorkoutSessionById(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSessionById,
          [sessionId],
        ),
        returnValue: _i6.Future<_i3.WorkoutSessionModel?>.value(),
        returnValueForMissingStub: _i6.Future<_i3.WorkoutSessionModel?>.value(),
      ) as _i6.Future<_i3.WorkoutSessionModel?>);

  @override
  _i6.Future<List<_i3.WorkoutSessionModel>> getWorkoutHistory({
    int? limit,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutHistory,
          [],
          {
            #limit: limit,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i6.Future<List<_i3.WorkoutSessionModel>>.value(
            <_i3.WorkoutSessionModel>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.WorkoutSessionModel>>.value(
                <_i3.WorkoutSessionModel>[]),
      ) as _i6.Future<List<_i3.WorkoutSessionModel>>);

  @override
  _i6.Future<List<_i7.ExerciseLogModel>> getExerciseHistory(
    String? exerciseName, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseHistory,
          [exerciseName],
          {#limit: limit},
        ),
        returnValue: _i6.Future<List<_i7.ExerciseLogModel>>.value(
            <_i7.ExerciseLogModel>[]),
        returnValueForMissingStub: _i6.Future<List<_i7.ExerciseLogModel>>.value(
            <_i7.ExerciseLogModel>[]),
      ) as _i6.Future<List<_i7.ExerciseLogModel>>);

  @override
  _i6.Future<List<String>> getAllExerciseNames() => (super.noSuchMethod(
        Invocation.method(
          #getAllExerciseNames,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<List<_i4.ExerciseLibraryModel>> getExerciseLibrary() =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseLibrary,
          [],
        ),
        returnValue: _i6.Future<List<_i4.ExerciseLibraryModel>>.value(
            <_i4.ExerciseLibraryModel>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.ExerciseLibraryModel>>.value(
                <_i4.ExerciseLibraryModel>[]),
      ) as _i6.Future<List<_i4.ExerciseLibraryModel>>);

  @override
  _i6.Future<_i4.ExerciseLibraryModel?> getExerciseLibraryById(
          String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseLibraryById,
          [exerciseId],
        ),
        returnValue: _i6.Future<_i4.ExerciseLibraryModel?>.value(),
        returnValueForMissingStub:
            _i6.Future<_i4.ExerciseLibraryModel?>.value(),
      ) as _i6.Future<_i4.ExerciseLibraryModel?>);

  @override
  _i6.Future<_i4.ExerciseLibraryModel> createLibraryExercise(
          _i4.ExerciseLibraryModel? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLibraryExercise,
          [exercise],
        ),
        returnValue: _i6.Future<_i4.ExerciseLibraryModel>.value(
            _FakeExerciseLibraryModel_2(
          this,
          Invocation.method(
            #createLibraryExercise,
            [exercise],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.ExerciseLibraryModel>.value(
            _FakeExerciseLibraryModel_2(
          this,
          Invocation.method(
            #createLibraryExercise,
            [exercise],
          ),
        )),
      ) as _i6.Future<_i4.ExerciseLibraryModel>);

  @override
  _i6.Future<_i4.ExerciseLibraryModel> updateLibraryExercise(
          _i4.ExerciseLibraryModel? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLibraryExercise,
          [exercise],
        ),
        returnValue: _i6.Future<_i4.ExerciseLibraryModel>.value(
            _FakeExerciseLibraryModel_2(
          this,
          Invocation.method(
            #updateLibraryExercise,
            [exercise],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.ExerciseLibraryModel>.value(
            _FakeExerciseLibraryModel_2(
          this,
          Invocation.method(
            #updateLibraryExercise,
            [exercise],
          ),
        )),
      ) as _i6.Future<_i4.ExerciseLibraryModel>);

  @override
  _i6.Future<void> deleteLibraryExercise(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLibraryExercise,
          [exerciseId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i4.ExerciseLibraryModel>> watchExerciseLibrary() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchExerciseLibrary,
          [],
        ),
        returnValue: _i6.Stream<List<_i4.ExerciseLibraryModel>>.empty(),
        returnValueForMissingStub:
            _i6.Stream<List<_i4.ExerciseLibraryModel>>.empty(),
      ) as _i6.Stream<List<_i4.ExerciseLibraryModel>>);
}
